blank_issues_enabled: false
contact_links:
  - name: Questions/discussion
    url: https://community.home-assistant.io/t/custom-component-alarmo-browser-managed-alarm-system/238910
    about: Ask questions, discuss configuration, share your setup